# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='clatt',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='clong',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
