# Generated by Django 2.2.6 on 2019-10-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_auto_20191022_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
